import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { TestParameter, DoctorRecommendation, HealthStatus } from '../lib/types';

interface GenerateReportPDFParams {
  patientName: string;
  reportDate: string;
  overallStatus: HealthStatus;
  parameters: TestParameter[];
  simplifiedText: string;
  advice: string[];
  doctors: DoctorRecommendation[];
}

const STATUS_RGB: Record<HealthStatus, [number, number, number]> = {
  normal: [34, 197, 94],
  borderline: [245, 158, 11],
  abnormal: [239, 68, 68],
  unknown: [148, 163, 184],
};

const STATUS_ROW_RGB: Record<HealthStatus, [number, number, number]> = {
  normal: [240, 253, 244],
  borderline: [254, 252, 232],
  abnormal: [254, 242, 242],
  unknown: [249, 250, 251],
};

function addFooter(doc: jsPDF, pageCount: number): void {
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.getHeight();
    const pageWidth = doc.internal.pageSize.getWidth();
    doc.setDrawColor(226, 232, 240);
    doc.line(20, pageHeight - 20, pageWidth - 20, pageHeight - 20);
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(
      'Generated by MediSense | For informational purposes only | Consult a doctor for diagnosis',
      pageWidth / 2,
      pageHeight - 13,
      { align: 'center' }
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 7, {
      align: 'center',
    });
  }
}

export function generateReportPDF({
  patientName,
  reportDate,
  overallStatus,
  parameters,
  simplifiedText,
  advice,
  doctors,
}: GenerateReportPDFParams): void {
  const doc = new jsPDF({ format: 'a4', orientation: 'portrait' });
  const pageWidth = doc.internal.pageSize.getWidth();

  // ── HEADER BANNER ────────────────────────────────────────────────────────
  doc.setFillColor(74, 144, 226);
  doc.rect(0, 0, pageWidth, 36, 'F');

  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('🏥 MediSense', 20, 16);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Medical Report Analysis', 20, 27);

  doc.setFontSize(10);
  doc.text(`Patient: ${patientName}`, pageWidth - 20, 16, { align: 'right' });
  doc.text(`Report Date: ${reportDate}`, pageWidth - 20, 23, { align: 'right' });
  doc.text(
    `Generated: ${new Date().toLocaleDateString('en-IN')}`,
    pageWidth - 20,
    30,
    { align: 'right' }
  );

  // ── OVERALL STATUS ───────────────────────────────────────────────────────
  const [r, g, b] = STATUS_RGB[overallStatus];
  doc.setFillColor(r, g, b);
  doc.roundedRect(20, 44, pageWidth - 40, 14, 3, 3, 'F');
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(
    `Overall Health Status: ${overallStatus.toUpperCase()}`,
    pageWidth / 2,
    53,
    { align: 'center' }
  );

  // ── REPORT SUMMARY ───────────────────────────────────────────────────────
  let y = 68;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('What Your Report Means', 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  const splitText = doc.splitTextToSize(simplifiedText, pageWidth - 40);
  doc.text(splitText, 20, y);
  y += splitText.length * 5 + 10;

  // ── TEST PARAMETERS TABLE ────────────────────────────────────────────────
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('Test Parameters', 20, y);
  y += 4;

  autoTable(doc, {
    startY: y,
    head: [['Parameter', 'Value', 'Unit', 'Normal Range', 'Status']],
    body: parameters.map((p) => [
      p.parameter_name,
      p.value,
      p.unit,
      p.normal_range,
      p.status.toUpperCase(),
    ]),
    headStyles: { fillColor: [74, 144, 226], textColor: 255, fontStyle: 'bold' },
    bodyStyles: { fontSize: 9 },
    willDrawCell: (data) => {
      if (data.section === 'body') {
        const status = parameters[data.row.index]?.status ?? 'unknown';
        const [fr, fg, fb] = STATUS_ROW_RGB[status as HealthStatus] ?? STATUS_ROW_RGB.unknown;
        data.cell.styles.fillColor = [fr, fg, fb];
      }
    },
    margin: { left: 20, right: 20 },
  });

  // ── HEALTH RECOMMENDATIONS ───────────────────────────────────────────────
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 14;
  if (y > 240) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('Health Recommendations', 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  advice.forEach((item) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text(`• ${item}`, 24, y);
    y += 6;
  });

  // ── RECOMMENDED SPECIALISTS ──────────────────────────────────────────────
  if (doctors.length > 0) {
    y += 8;
    if (y > 240) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text('Consult These Specialists', 20, y);
    y += 4;

    autoTable(doc, {
      startY: y,
      head: [['Doctor', 'Specialty', 'Urgency', 'Contact']],
      body: doctors.map((d) => [
        d.doctor_name || '—',
        d.specialty,
        d.urgency.toUpperCase(),
        d.phone || '—',
      ]),
      headStyles: { fillColor: [74, 144, 226], textColor: 255, fontStyle: 'bold' },
      bodyStyles: { fontSize: 9 },
      margin: { left: 20, right: 20 },
    });
  }

  // ── FOOTERS ──────────────────────────────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  addFooter(doc, totalPages);

  // ── DOWNLOAD ─────────────────────────────────────────────────────────────
  const dateStr = new Date().toISOString().slice(0, 10);
  doc.save(`medisense-report-${dateStr}.pdf`);
}
